### ISSUE TITLE
[Feature]: More narrow window improvements

### ISSUE THREAD

**Issue by dagandrew** [sircharlo/meeting-media-manager#3872]
### Is your feature request related to a problem?

1. I've noticed some overlaps in Russian: ![image](https://github.com/user-attachments/assets/575d4889-3e7a-4f2d-8496-482a53fc0ab0)

2. ![image](https://github.com/user-attachments/assets/f4bdcf23-e416-460a-9334-903cf05d5091)
is there even a need for this button? because other meeting parts don't have it? 
![image](https://github.com/user-attachments/assets/cdcc7dfa-34ce-458c-9d21-03a3237e80ba)

3. Also this one: it breaks the layout because the last button is wide
 ![image](https://github.com/user-attachments/assets/00817974-97f8-49e3-a4d9-6b0c7653074c)

4. and one final one - could the gap between description and input field here be a little bit bigger? It seems that it's too close
![image](https://github.com/user-attachments/assets/499fad3a-bdde-4fe0-b748-c9a20e5070ed)
and between descriptions and shortcuts
![image](https://github.com/user-attachments/assets/10ed44a8-c326-460f-b73d-58e0cf6ff715)

### Describe the solution you'd like

1. just keep the music icon as you do with those ones when the window is narrow enough
![image](https://github.com/user-attachments/assets/e94683be-ab0a-4af6-9eab-78b259f089e7)
2. Remove it all together because other parts don't have it and there is import button at the top
3. Remove text from 'stop mirroring' button when the window is narrow enough and maybe make it red, so it could be intuitive (it would be great even if the window is wide)
4. Increase the gap just a little

### Describe alternatives you've considered

do the same what you did here 
![image](https://github.com/user-attachments/assets/1e74e84c-e0b4-4285-9632-5761c7c5b1d8)
for this button for narrow windows? I mean that if the window is narrow enough and shrink the button to fixed width and cut the words? 

### Confirmations

- [X] I confirm that I have read the documentation website.
- [X] I confirm that I have searched through the existing issues to make sure my feature request is not a duplicate.
- [X] I confirm that I have searched through the existing discussions to make sure my feature request is not a duplicate.

**Comment by mtdvlpr** [comment]
1. Fixed in daadb8f8572e4949fa743907449cfca71fe7fcac
2. The button is a shortcut to immediately add media to the Living as Christians section instead of adding it at the top and dragging it there. It's only available for the Living as Christians section, because that's where Governing Body updates and local needs media is often added.
3. Fixed in 6c210bce89b254f940468798718e2de0b8365b1f
4. Fixed in daadb8f8572e4949fa743907449cfca71fe7fcac

**Comment by dagandrew** [comment]
First is still present in beta.1. Maybe it's a different element for a weekend's talk?

**Comment by mtdvlpr** [comment]
> First is still present in beta.1. Maybe it's a different element for a weekend's talk?

You're right. I missed a button, thanks! Fixed in f75edfe4c84705269a203188d09531f4be3f1459

**Comment by mtdvlpr** [comment]
> it seems that first issue is back in latest beta

Good catch! This was regressed in f73bb69406f77e17c39fc5f3433c743d9fa0b53a. I've fixed it (again) in 28fbdd912d2e653324fa8c2c4fa89540d4773837
