### ISSUE TITLE
Semana 28 de abril de 2025

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/meeting-media-manager#4289]
### What happened?

Não semana de 28 de abril de 2025 não aparece nenhuma mídia no M3

### To Reproduce

1. Go to '...' Vai para a semana 28 de abril de 2025
2. Click on '....' dia da reunião
3. Do '....'
4. See error Sem mídias

![Image](https://github.com/user-attachments/assets/6c4e83a6-daca-4560-ac08-d81daf5d293f)

### What did you expect to happen?

Aparecesse as mídias da semana.

### Version

v253.1

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell

```

### Confirmations

- [x] I confirm that I have read the documentation website.
- [x] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [x] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by sircharlo** [comment]
I think this is fixed in https://github.com/sircharlo/meeting-media-manager/commit/4de6ed003dd9269735a16b9e819b16274eed8a80. Please try the latest beta once it's released within the next few hours to confirm.

**Comment by e-Feitosa** [comment]
@sircharlo, this message appears on my M3, both in the standard version and the beta, but the media hasn’t downloaded here. I’ve already done a clean installation of M3 and the problem persists. I’m using Windows 11.
 
![Image](https://github.com/user-attachments/assets/652b50f1-9c48-4afd-93e4-a8506679023f)

[v25.3.2-beta.4]
⬇️
![Image](https://github.com/user-attachments/assets/a6c88ccf-897c-4ab4-ace7-b4ab5a8ee462)

I believe this error is also related to the new song 161 that will be used this week (7/4) and in the booklet for the week that is showing the error, there is only the instruction to use the song. I think the M3 isn’t understanding to download this week’s song, but the other media files aren’t downloading in the beta version either.
⬇️
![Image](https://github.com/user-attachments/assets/4f25383e-5c77-46a6-97dc-bec0d71ca964)

**Comment by e-Feitosa** [comment]
> Try v25.3.2-beta.6 to see if the problem is now resolved. 😄

Fixed the issue!
**Very good.**
Thank you for everyone's time and effort.
