### ISSUE TITLE
[Bug]: Strange behaviour with WT Study Images

### ISSUE THREAD

**Issue by GrahamR-AU** [sircharlo/meeting-media-manager#4351]
### What happened?

Firstly, some background info: I have M3 installed on my 2 Windows 11 laptops at home. We do not use it at our Kingdom Hall, but I find it very useful for our family meeting preparation at home.

On the laptop that we use for meeting preparation: With the update to v25.4.0 the behaviour of  the WT Stiudy images has changed. For example the study for this week (W/E 20/04/2025) has the songs and only one image. Before I updated it had the songs and two images (as does JW Library). For next week's study it only has two images, whereas JW Library has twelve!

![Image](https://github.com/user-attachments/assets/5a9c4c6b-22ea-45f4-8cb0-d03b492802fe)

On the other laptop: As above, but it duplicates the meeting, with the first instance showing the songs and the full complement of images, the second instance shows the songs and the reduced number of images.

![Image](https://github.com/user-attachments/assets/2bd40027-0893-4215-811f-d1b06c72d554)
![Image](https://github.com/user-attachments/assets/cd54f2d5-3d53-4481-956c-561a610940b7)

I'm at a loss to explain why the behaviour is different between machines!

### To Reproduce

1. Open M3
2. Go to any weekend meeting
3. See the above behaviour

### What did you expect to happen?

I expected normal behaviour.

### Version

v25.4.0

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
I couldn't seem to make this happen?
```

### Confirmations

- [x] I confirm that I have read the documentation website.
- [x] I confirm that I have searched through the existing issues to make sure my bug report is not a duplicate.
- [x] I confirm that I have searched through the existing discussions to make sure my bug report is not a duplicate.

**Comment by mtdvlpr** [comment]
@sircharlo, could this be due to 21c54d80def2bb7ae0bfbe180c92cc09ff1da6f5 or 9434eefd1e41e409d4a210bca671e03f15a28d14?

**Comment by mtdvlpr** [comment]
> [@sircharlo](https://github.com/sircharlo), could this be due to [21c54d8](https://github.com/sircharlo/meeting-media-manager/commit/21c54d80def2bb7ae0bfbe180c92cc09ff1da6f5) or [9434eef](https://github.com/sircharlo/meeting-media-manager/commit/9434eefd1e41e409d4a210bca671e03f15a28d14)?

Nvm, I found the issue!

**Comment by mtdvlpr** [comment]
This has been fixed in b906ba3e68dc8a74f738ae673f598ad9878d2f5b.

@sircharlo, I'm not sure I've fixed it in the right way, so please verify your logic is still in tact.

**Comment by GrahamR-AU** [comment]
@mtdvlpr This issue is not completely fixed, for me at least. The behaviour has changed. My first attempt (on the 2nd PC mentioned in the OP) there was no change. So I removed the entire profile from %appdata%\Meeting Media Manager. The started the program and created a new profile. Now:
For this week's WT Study, still missing an image.

![Image](https://github.com/user-attachments/assets/2254496d-1be3-4615-a50a-0569039d53f7)

For next week's WT Study, still duplicating some, but not all, images, but not songs.

![Image](https://github.com/user-attachments/assets/63480053-b3fe-4f56-aeb4-4433832069ec)

![Image](https://github.com/user-attachments/assets/a55ec779-fb76-46f0-9ac2-e2082809233e)

![Image](https://github.com/user-attachments/assets/c706216a-bfc6-4641-9a4f-468fef5c46e1)

![Image](https://github.com/user-attachments/assets/0bf4e5fc-8485-402e-8f52-0d5c9a5dcd81)

Please reopen this issue, it doesn't let me...

**Comment by GrahamR-AU** [comment]
I also just noticed that the first image for this coming week's midweek meeting is also duplicated (last week's and next week's same), as is the image from the Congregation Bible Study, the final song is in the wrong position.

Thanks for your hard work brothers!

![Image](https://github.com/user-attachments/assets/d0e42620-ee31-43b9-95e9-b197188fb3c0)

![Image](https://github.com/user-attachments/assets/aa59e213-1c5e-4cdd-8c16-05619731437a)

**Comment by mtdvlpr** [comment]
Thank you for reporting this so promptly and sorry for the incomplete fix! It has now been fixed correctly in e3e45a48f819719343ee2492e3ad95172cc7b873. Duplicates will automatically be removed in the next release, so no manual action should be required. If you're still missing some media, you should go to the Settings page and at the top, open the Tools and perform the "Clear all cache files" action.
